*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZMATERIAL_STOCK_CHECKER_PPK.

TYPES: BEGIN OF TY_MARA,
         MATNR    TYPE MATNR,
         MTART    TYPE MTART,
         MBRSH    TYPE MBRSH,
         WERKS    TYPE WERKS_D,
         LGORT    TYPE LGORT_D,
         LABST    TYPE LABST,
         UMLME    TYPE UMLMD,
         INSME    TYPE INSME,
       END OF TY_MARA.

DATA: ITAB TYPE STANDARD TABLE OF TY_MARA,
      WA   TYPE TY_MARA.

DATA: LV_MATNR TYPE MATNR.
SELECT-OPTIONS: S_MATNR FOR LV_MATNR.

DATA: ITAB_FIELDCAT TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT   TYPE SLIS_FIELDCAT_ALV,
      WA_LAYOUT     TYPE SLIS_LAYOUT_ALV.

START-OF-SELECTION.
  SELECT ALIAS_MARA~MATNR
         ALIAS_MARA~MTART
         ALIAS_MARA~MBRSH
         ALIAS_MARD~WERKS
         ALIAS_MARD~LGORT
         ALIAS_MARD~LABST
         ALIAS_MARD~UMLME
         ALIAS_MARD~INSME
 FROM MARA AS ALIAS_MARA INNER JOIN MARD AS ALIAS_MARD ON ALIAS_MARA~MATNR = ALIAS_MARD~MATNR
 INTO TABLE ITAB
 WHERE ALIAS_MARA~MATNR IN S_MATNR AND ALIAS_MARD~WERKS = '1710'.

  IF ITAB IS INITIAL.
    MESSAGE: 'RECORD NOT FOUND' TYPE 'E'.
  ELSE.
    MESSAGE: 'RECORDS FOUND' TYPE 'S'.
  ENDIF.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL NUMBER'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MTART'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL TYPE'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MBRSH'.
  WA_FIELDCAT-SELTEXT_L = 'INDUSTRY'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LGORT'.
  WA_FIELDCAT-SELTEXT_L = 'STORAGE LOCATION'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LABST'.
  WA_FIELDCAT-SELTEXT_L = 'CURRENT STOCK'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'UMLME'.
  WA_FIELDCAT-SELTEXT_L = 'STOCK IN TRANSFER '.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'INSME'.
  WA_FIELDCAT-SELTEXT_L = 'STOCK IN QUALITY INSPECTION'.
  WA_FIELDCAT-JUST = 'C'.
  APPEND WA_FIELDCAT TO ITAB_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  WA_LAYOUT-ZEBRA = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK      = ' '
*     I_BYPASSING_BUFFER     = ' '
*     I_BUFFER_ACTIVE        = ' '
      I_CALLBACK_PROGRAM     = SY-REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
*     I_CALLBACK_USER_COMMAND           = ' '
      I_CALLBACK_TOP_OF_PAGE = 'HEADING'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME       =
*     I_BACKGROUND_ID        = ' '
*     I_GRID_TITLE           =
*     I_GRID_SETTINGS        =
      IS_LAYOUT              = WA_LAYOUT
      IT_FIELDCAT            = ITAB_FIELDCAT
*     IT_EXCLUDING           =
*     IT_SPECIAL_GROUPS      =
*     IT_SORT                =
*     IT_FILTER              =
*     IS_SEL_HIDE            =
*     I_DEFAULT              = 'X'
*     I_SAVE                 = ' '
*     IS_VARIANT             =
*     IT_EVENTS              =
*     IT_EVENT_EXIT          =
*     IS_PRINT               =
*     IS_REPREP_ID           =
*     I_SCREEN_START_COLUMN  = 0
*     I_SCREEN_START_LINE    = 0
*     I_SCREEN_END_COLUMN    = 0
*     I_SCREEN_END_LINE      = 0
*     I_HTML_HEIGHT_TOP      = 0
*     I_HTML_HEIGHT_END      = 0
*     IT_ALV_GRAPHICS        =
*     IT_HYPERLINK           =
*     IT_ADD_FIELDCAT        =
*     IT_EXCEPT_QINFO        =
*     IR_SALV_FULLSCREEN_ADAPTER        =
*     O_PREVIOUS_SRAL_HANDLER           =
*   IMPORTING
*     E_EXIT_CAUSED_BY_CALLER           =
*     ES_EXIT_CAUSED_BY_USER =
    TABLES
      T_OUTTAB               = ITAB
*   EXCEPTIONS
*     PROGRAM_ERROR          = 1
*     OTHERS                 = 2
    .
  IF SY-SUBRC <> 0.
* IMPLEMENT SUITABLE ERROR HANDLING HERE
  ENDIF.

FORM HEADING.

  DATA: ITAB_HEADER TYPE STANDARD TABLE OF SLIS_LISTHEADER,
        WA_HEADER   TYPE SLIS_LISTHEADER.

  WA_HEADER-TYP = 'H'.
  WA_HEADER-INFO = 'MATERIAL DATA'.
  APPEND WA_HEADER TO ITAB_HEADER.
  CLEAR WA_HEADER.


  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = ITAB_HEADER                 " COMMENT BLOCK
*     I_LOGO             =
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =                  " USE ALV FORM ("X")
    .
ENDFORM.
